# path thingy
SRC = src
BUILD = Builds/TestBuilds
LINKER = linker/link.ld
INCLUDE = include

# tools
CC = arm-none-eabi-gcc
AS = arm-none-eabi-as
LD = arm-none-eabi-ld
OBJCOPY = arm-none-eabi-objcopy

# targets
KERNEL_ELF = $(BUILD)/kernel.elf
KERNEL_IMG = $(BUILD)/kernel.img
C_SOURCES = $(SRC)/bgudakrnl.c
ASM_SOURCES = $(SRC)/boot.s

# default builds
all: $(KERNEL_IMG)

# redundency
$(BUILD):
	mkdir -p $(BUILD)

# assembly stuff
$(BUILD)/boot.o: $(ASM_SOURCES) | $(BUILD)
	$(AS) -o $@ $<

# c stuff
$(BUILD)/bgudakrnl.o: $(C_SOURCES) | $(BUILD)
	$(CC) -c -mcpu=arm1176jzf-s -O2 -Wall -nostdlib -nostartfiles -ffreestanding -I$(INCLUDE) -o $@ $<

# link elf-ing
$(KERNEL_ELF): $(BUILD)/boot.o $(BUILD)/bgudakrnl.o
	$(LD) -T $(LINKER) -o $@ $^

# img-ing
$(KERNEL_IMG): $(KERNEL_ELF)
	$(OBJCOPY) $< -O binary $@

#cleanup
clean:
	rm -rf $(BUILD)/*.o $(BUILD)/*.elf $(BUILD)/*.img
